#!/usr/bin/env bash
# localhost ve facebook.com-un IP-lerini deyisdirir

sed 's/^127\.0\.0\.1[[:space:]]\+localhost$/127.0.0.2 localhost/' /etc/hosts > /tmp/hosts_new
cat /tmp/hosts_new > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
