#!/usr/bin/env bash
# localhost -> 127.0.0.2 ve facebook.com -> 8.8.8.8 kimi konfiqurasiya edir

sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost$/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
